# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.1
  aws-ecs: circleci/aws-ecs@3.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          registry-id: AWS_ECR_REGISTRY_ID
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          cluster: 'cloud-service-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX},tag=${CIRCLE_SHA1}'
          family: 'Main'
          requires:
            - aws-ecr/build-and-push-image
